# Generated by Django 4.2.4 on 2023-09-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Usuario',
        ),
    ]
