# Generated by Django 4.2.4 on 2023-11-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
