# Generated by Django 4.2.4 on 2023-09-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_task_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='edad',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='ejemplo.es@gmail.com', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='jornada',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
