# Generated by Django 4.2.4 on 2023-09-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_edad_usuario_telefono_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='jornada',
            field=models.CharField(choices=[('vespertino', 'Vespertino'), ('duirno', 'Duirno')], default='duirno', max_length=10),
        ),
    ]
