# Generated by Django 4.2.4 on 2023-09-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_usuario_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='jornada',
            field=models.CharField(choices=[('duirno', 'Duirno'), ('vespertino', 'Vespertino')], default='duirno', max_length=10),
        ),
    ]
