# Generated by Django 4.2.4 on 2023-09-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='ejemplo.es@gmail.com', max_length=35),
        ),
    ]
